<a href="https://colab.research.google.com/github/sajan-sarker/machine-learning/blob/main/numpy_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.random.random()

0.0638004121976381

In [6]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [9]:
np.random.random(6)

array([0.34556073, 0.39676747, 0.53881673, 0.41919451, 0.6852195 ,
       0.20445225])

In [12]:
np.random.uniform(3, 10)

7.693272571248816

In [21]:
np.random.uniform(3,10)

3.716341001794781

In [17]:
np.random.uniform(1, 100, 10)

array([87.93610784, 10.73633655, 42.68965488, 95.83106348, 53.78336321,
       69.49583428, 32.23604747, 68.96359184, 83.62794152,  2.81053946])

In [19]:
np.random.uniform(1, 100, 10).reshape(2, 5)

array([[13.87282864,  2.91732883, 68.20471776, 21.95118348, 27.28911928],
       [49.66574277,  6.28289197, 57.83764294, 15.52612892, 59.34124815]])

In [22]:
np.random.randint(1, 10)

8

In [23]:
np.random.randint(1, 10, 5)

array([2, 2, 4, 1, 9])

In [24]:
np.random.randint(1, 10, 15).reshape(3,5)

array([[7, 5, 6, 7, 3],
       [6, 8, 9, 5, 5],
       [8, 8, 5, 1, 3]])

In [27]:
a = np.random.randint(1, 10, 15)
a

array([2, 8, 9, 5, 1, 2, 9, 3, 4, 2, 3, 8, 3, 7, 1])

In [28]:
np.max(a)

9

In [29]:
a[np.argmax(a)]

9

In [31]:
np.argmax(a)

2

In [33]:
b = np.random.randint(1, 10, 6)
b

array([1, 7, 6, 2, 5, 7])

In [40]:
b[b%2 == 1]= 0
b

array([0, 0, 6, 2, 0, 0])

In [42]:
# where(condition, true, false)
c = np.random.randint(1, 50, 6)
c

array([44,  7, 14, 16, 25, 10])

In [43]:
np.where(c%2 == 1, -1, c)

array([44, -1, 14, 16, -1, 10])

In [44]:
c

array([44,  7, 14, 16, 25, 10])

In [45]:
np.sort(c)

array([ 7, 10, 14, 16, 25, 44])

In [47]:
d = np.random.randint(1, 50, 10)
d = np.sort(d)
d

array([14, 15, 17, 24, 29, 41, 43, 46, 46, 48])

In [50]:
# [14, 15, 17, 24, 29, 41, 43, 46, 46, 48]
np.percentile(d, 25) # 25% of array is: 17< 25% <24

18.75