<a href="https://colab.research.google.com/github/sajan-sarker/machine-learning/blob/main/numpy_broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
# scenario 1

a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,16).reshape(2,4)
print(a1)
print(a2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [7]:
a1 + a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [13]:
# scenario 2

a3 = np.arange(9).reshape(3,3)
a4 = np.arange(3).reshape(1,3)
print(a3)
print(a4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]]


In [15]:
print(a3 + a4) # a4 is adding with each row of a3.

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


**Rules for Broadcasting**

In [17]:
# If x=m and y=n, operation will take place
a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8, 16).reshape(2,4)

print(a1+a2)

[[ 8 10 12 14]
 [16 18 20 22]]


In [21]:
# If x=1 and y=n then also operatino will take place(same dimentsion)
a5 = np.arange(3).reshape(1,3)
a6 = np.arange(12).reshape(4,3)
print(a5)
print(a6)
print(a5+a6)

[[0 1 2]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [24]:
# If x= 1 and y!= n then operation will not take place

a7 = np.arange(3).reshape(1,3)
a8 = np.arange(16).reshape(4,4)
#print(a7+a8)   # error will occurre

In [25]:
# If x= 1 and n = 1 then y= m then operation will take place

a9 = np.arange(3).reshape(1,3)
a10 = np.arange(3).reshape(3,1)
print(a9 + a10)

[[0 1 2]
 [1 2 3]
 [2 3 4]]
